# Generated by Django 5.1.3 on 2024-11-25 23:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_iban', models.CharField(max_length=30)),
                ('new_iban', models.CharField(max_length=30)),
                ('old_type', models.CharField(max_length=30)),
                ('new_type', models.CharField(max_length=30)),
                ('user_action', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('cantidad_tarjeta_debito', models.IntegerField()),
                ('cantidad_tarjeta_credito', models.IntegerField()),
                ('cantidad_chequera', models.IntegerField()),
                ('caja_ahorro_pesos', models.BooleanField()),
                ('caja_ahorro_dolares', models.BooleanField()),
                ('cuenta_corriente', models.BooleanField()),
                ('max_descubierto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_retiro_diario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_transferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_transferencia_recibida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('autorizar_transferencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('moneda', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_surname', models.CharField(max_length=30)),
                ('customer_dni', models.CharField(max_length=30)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_operacion', models.CharField(max_length=30)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('aprobado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_number', models.IntegerField()),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_surname', models.CharField(max_length=30)),
                ('employee_hire_date', models.DateField(default=django.utils.timezone.now)),
                ('employee_dni', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.sucursal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='entidad_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.tipo_cliente'),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iban', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.cliente')),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.tipo_cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cvv', models.IntegerField()),
                ('fecha_otorgamiento', models.DateField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.cliente')),
                ('tipo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint_8.tipo_tarjeta')),
            ],
        ),
    ]
