# Generated by Django 5.1.3 on 2024-11-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0002_alter_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sprint_8.cuenta'),
            preserve_default=False,
        ),
    ]
