# Generated by Django 5.1.3 on 2024-11-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0003_remove_prestamo_cliente_prestamo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='direcciones',
            field=models.ManyToManyField(to='sprint_8.direccion'),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='branch',
        ),
        migrations.AddField(
            model_name='empleado',
            name='branch',
            field=models.ManyToManyField(to='sprint_8.sucursal'),
        ),
    ]
