# Generated by Django 5.1.3 on 2024-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0004_cuenta_direcciones_remove_empleado_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='direcciones',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direcciones',
            field=models.ManyToManyField(to='sprint_8.direccion'),
        ),
    ]
