# Generated by Django 5.1.3 on 2024-11-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0005_remove_cliente_branch_remove_cuenta_direcciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='customer',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sprint_8.cuenta'),
            preserve_default=False,
        ),
    ]
