# Generated by Django 5.1.3 on 2024-11-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0007_alter_prestamo_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='iban',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
