# Generated by Django 5.1.3 on 2024-11-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0008_alter_cuenta_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='destino',
            field=models.CharField(default='n/a', max_length=30),
            preserve_default=False,
        ),
    ]
