# Generated by Django 5.1.3 on 2024-11-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0009_movimientos_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sprint_8.sucursal'),
            preserve_default=False,
        ),
    ]
