# Generated by Django 5.1.3 on 2024-11-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0011_empleado_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria_cuenta',
            old_name='new_iban',
            new_name='new_cbu',
        ),
        migrations.RenameField(
            model_name='auditoria_cuenta',
            old_name='old_iban',
            new_name='old_cbu',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='iban',
            new_name='cbu',
        ),
    ]
