# Generated by Django 5.1.3 on 2024-12-06 01:26

import django.utils.timezone
import sprint_8.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_8', '0013_remove_empleado_usuario_empleado_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_expiracion',
            field=models.DateField(default=sprint_8.models.Tarjeta.default_expiration_date),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_otorgamiento',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
